apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: alpine-demo
  template:
    metadata:
      labels:
        app: alpine-demo
    spec:
      containers:
      - name: alpine
        image: alpine:3.19
        command: ["sleep", "3600"]
